image: docker:latest

stages:
  - build
  - push_gitlab
  - push_dockerhub

services:
  - docker:19.03.12-dind

Build:
  stage: build
  script:
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA .
    - docker login -u "$CI_REGISTRY_USER" -p "${CI_REGISTRY_TOKEN}" $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA $CI_PROJECT_PATH:$CI_COMMIT_SHA
    - echo -n $DOCKER_HUB_TOKEN | docker login -u "$DOCKER_HUB_USER" --password-stdin
    - docker push $CI_PROJECT_PATH:$CI_COMMIT_SHA


Push latest gitlab:
  stage: push_gitlab
  only:
    - master
  script:
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker login -u "$CI_REGISTRY_USER" -p "${CI_REGISTRY_TOKEN}" $CI_REGISTRY
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest
    - echo -n $DOCKER_HUB_TOKEN | docker login -u "$DOCKER_HUB_USER" --password-stdin
    - docker tag $CI_PROJECT_PATH:$CI_COMMIT_SHA $CI_PROJECT_PATH:latest
    - docker push $CI_PROJECT_PATH:latest

Push tag gitlab:
  stage: push_gitlab
  only:
    - tags
  script:
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker login -u "$CI_REGISTRY_USER" -p "${CI_REGISTRY_TOKEN}" $CI_REGISTRY
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    - echo -n $DOCKER_HUB_TOKEN | docker login -u "$DOCKER_HUB_USER" --password-stdin
    - docker tag $CI_PROJECT_PATH:$CI_COMMIT_SHA $CI_PROJECT_PATH:$CI_COMMIT_REF_NAME
    - docker push $CI_PROJECT_PATH:$CI_COMMIT_REF_NAME
